### ISSUE TITLE
GestureRecorder.pde occasionally crashes from NullPointerExceptions of gestureRecording.savedFilename on line 250

### ISSUE THREAD

**Issue by Jakersnorth** [jonfroehlich/CSE599Sp2019#1]
For me at least, GestureRecorder will randomly hit a NullPointerException at line 250 for gestureRecording.savedFilename at the first instance of trying to draw that text when a gesture has been completed. Sometimes it will happen after recording the 2nd gesture, sometimes after the 30th but I have not yet seen an instance of recording all the gestures without this happening at least 1. My quick fix has been to add a null check of the sort `if(gestureRecording.savedFilename != null) { 
        text(gestureRecording.savedFilename, xPixelStartGesture + 2, 50);
      } else {
        System.out.println("missing file name");
}`
which is keeping the application from totally crashing and does not seem to be having any adverse effects on saving the files, but this seems more like a bandaid then a solution.

**Comment by jonfroehlich** [comment]
Strange, I never saw this in my own testing. Thanks for posting this (and your fix!). We can discuss tomorrow in class and see if others have been running into the same problem.

**Comment by t-rasmud** [comment]
I am running into this issue as well. As a workaround, I added the line `while (gestureRecording.savedFilename == null) { }`

**Comment by jonfroehlich** [comment]
You guys are just trying to make me look bad! :-P

I still haven't seen this issue but will load up GestureRecorder.pde again to investigate more...

Sorry about this and thanks for posting!

Stay tuned!!

**Comment by jonfroehlich** [comment]
OK, I just looked into it. I didn't see the problem myself but I could see how it could happen so just added in a simple null check.
