### ISSUE TITLE
Port Error Exception

### ISSUE THREAD

**Issue by nicolekriley** [jonfroehlich/CSE599Sp2019#2]
Whenever I try to run the program and run gestures I get an index array out of bounds exception for my correct port (determined to be 0 from both using the program you provided for ports and by using arduino). This causes the program to run until I try to press space again to say a gesture is finished. 

This is my error: 
**All Available Serial Ports**[0] "COM3"
Make sure to change ARDUINO_SERIAL_PORT_INDEX to the correct port number!java.lang.ArrayIndexOutOfBoundsException: 1 with nothing else. 

I double checked I changed the number several times and I have. I also tried different numbers in case. In that case the error changes slightly. 

**All Available Serial Ports**[0] "COM3"
Make sure to change ARDUINO_SERIAL_PORT_INDEX to the correct port number!java.lang.ArrayIndexOutOfBoundsException: 1
	at GestureRecorder.setup(GestureRecorder.java:97)
	at processing.core.PApplet.handleDraw(PApplet.java:2412)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316) 

I am not sure what is going on and I am looking through to figure out what is wrong but it is causing me problems with recording my gesture set.

**Comment by jonfroehlich** [comment]
It looks like you only have one active port, which is on index 0. Did you set `ARDUINO_SERIAL_PORT_INDEX` equal to `0`?

That is: `ARDUINO_SERIAL_PORT_INDEX = 0`

**Comment by jonfroehlich** [comment]
Also, you need to not have any other Processing program running that might be accessing the port (for example, not the ListSerialPorts.pde program) and no Serial Monitor or Serial Plotter window opened (in Arduino).

Only one resource on your computer can access a serial port at a time...

**Comment by jonfroehlich** [comment]
Please keep me updated. Happy to look tomorrow during class as well.

And can you post what line 97 is? On my system, line 97 is a blank line...

![image](https://user-images.githubusercontent.com/1621749/57663822-73406180-75aa-11e9-9079-688a43657349.png)

**Comment by nicolekriley** [comment]
I set the port equal to 0. All other programs for processing were not running. 97 is also a blank line for me and corresponds to the same spot in your file.

**Comment by jonfroehlich** [comment]
OK, I'll take a look tomorrow!
